import Defeater

/-
  Smoke.lean — smoke test executable.

  Reports the load-bearing facts of the defeater artifact at
  runtime. Every claim below is a Lean theorem; the executable just
  prints that the kernel checked it at compile time.
-/

open Defeater
open Defeater.Demo

def main : IO Unit := do
  IO.println "defeater — smoke test"
  IO.println "====================="
  IO.println ""
  IO.println "Object substrate: ground propositional, atoms = String."
  IO.println "    DefRule.validUnder env : (∀ p ∈ prems, env p) → env concl"
  IO.println "    Concl.sound : ungated forward chaining is sound  ✓"
  IO.println ""
  IO.println "Tower layer:"
  IO.println "    SoundDefeater env : (rule, trigger, undercutters, defeats)"
  IO.println "    defeats : env trigger → (no undercutter) → ¬ env concl"
  IO.println "    Tower env : rules + rung-indexed facts + rung-indexed defeaters"
  IO.println "    ConclAt T n : level-indexed derivability  ✓"
  IO.println ""
  IO.println "Conditional rung soundness:"
  IO.println "    Tower.rung_sound : every rung is sound under the env that"
  IO.println "      satisfies its facts and validates its undefeated rules  ✓"
  IO.println "    (conditional on rule-validity hypothesis)"
  IO.println ""
  IO.println "Bridge theorem (certificates earn their keep):"
  IO.println "    Tower.undefeated_valid_under_coverage : under coverage"
  IO.println "      (every env-invalid rule has a firing defeater),"
  IO.println "      undefeated rules are valid under env  ✓"
  IO.println ""
  IO.println "Stabilization:"
  IO.println "    Tower.tower_stabilizes : if the tower admits no facts or"
  IO.println "      defeaters past rung K, conclusions are constant from K  ✓"
  IO.println ""
  IO.println "Tweety scenario (rocket-strapped penguin):"
  IO.println "    rule:    bird ⇒ flies"
  IO.println "    rung 0:  bird"
  IO.println "    rung 1:  penguin  + defeater (penguin defeats bird ⇒ flies,"
  IO.println "                                  undercut by rocket)"
  IO.println "    rung 2:  rocket"
  IO.println ""
  IO.println "    rung0_concludes_flies   : ConclAt tweetyTower 0 \"flies\"  ✓"
  IO.println "    rung1_no_flies          : ¬ ConclAt tweetyTower 1 \"flies\"  ✓"
  IO.println "    rung2_concludes_flies   : ConclAt tweetyTower 2 \"flies\"  ✓"
  IO.println ""
  IO.println "    The conclusion sequence: flies → ¬flies → flies."
  IO.println "    Level-indexed non-monotonicity, witnessed in Lean."
  IO.println ""
  IO.println "Soundness applied to the demo:"
  IO.println "    tweety_rung2_sound : every conclusion at rung 2 holds in"
  IO.println "      tweetyEnv (rung_sound instantiated end-to-end)  ✓"
  IO.println ""
  IO.println "Stability applied to the demo:"
  IO.println "    tweetyTower_stabilizes : conclusions are constant for"
  IO.println "      n ≥ 2 (tower_stabilizes corollary)  ✓"
  IO.println ""
  IO.println "Reflective layer (defeaters fire on prior-rung CONCLUSIONS,"
  IO.println "not just asserted facts):"
  IO.println "    Tower.ReflConclAt T n : stratified — body for n+1 references"
  IO.println "      only ReflConclAt T n, sidesteps negative-occurrence  ✓"
  IO.println "    Tower.refl_rung_sound : per-rung soundness for reflective"
  IO.println "      semantics  ✓"
  IO.println ""
  IO.println "Reflective Tweety scenario:"
  IO.println "    rules:   bird ⇒ flies  ;  penguin ⇒ cantFly"
  IO.println "    rung 0:  facts {bird, penguin}; both rules fire"
  IO.println "             → conclusions include flies AND cantFly (DERIVED)"
  IO.println "    rung 1:  defeater of bird⇒flies, trigger = cantFly"
  IO.println "             defeater fires REFLECTIVELY on rung-0 inference"
  IO.println "             → flies no longer concluded; cantFly still concluded"
  IO.println ""
  IO.println "    rung0_concludes_flies         ✓"
  IO.println "    rung0_concludes_cantFly       ✓ (derived, observable to upper rung)"
  IO.println "    rung1_no_flies                ✓ (reflective defeat fires)"
  IO.println "    rung1_concludes_cantFly       ✓ (penguin⇒cantFly undisturbed)"
  IO.println "    reflDemo_rung1_sound          ✓ (bridge theorem applied:"
  IO.println "                                     coverage at rung 1 → env-soundness)"
  IO.println ""
  IO.println "Trust hierarchy (rung index = authority lattice):"
  IO.println "    sources:  junior witness  <  senior witness  <  forensic"
  IO.println "    rules:    junior testimony ⇒ redCoat"
  IO.println "              senior testimony ⇒ blueCoat"
  IO.println "              forensic report  ⇒ greenCoat"
  IO.println "    defeaters: senior overrides junior; forensic overrides senior"
  IO.println ""
  IO.println "    rung 0:  redCoat   (only junior has spoken)"
  IO.println "    rung 1:  blueCoat  (senior outranks junior)"
  IO.println "    rung 2:  greenCoat (forensic outranks senior)"
  IO.println ""
  IO.println "    trust_cascade  ✓ (conclusion shifts as authority ascends)"
  IO.println ""
  IO.println "Nixon Diamond (textbook symmetric conflict; Reiter):"
  IO.println "    rules:    Quaker ⇒ pacifist  ;  Republican ⇒ nonpacifist"
  IO.println "    defeaters: each rule's concl is the other's trigger"
  IO.println "    facts at rung 0: {quaker, republican}"
  IO.println ""
  IO.println "    nixon_baseline_at_rung0      ✓ (both concluded; pre-defeat)"
  IO.println "    nixon_post_defeat_at_rung1   ✓ (neither concluded)"
  IO.println "    nixon_diamond_irresolution   ✓ (rung-0 / rung-1 contrast)"
  IO.println "    nixon_parity                 ✓ (∀ k: both at 2k, neither at 2k+1)"
  IO.println ""
  IO.println "Reflective non-stabilization (the syntactic stabilization theorem"
  IO.println "does NOT lift unconditionally to the reflective layer):"
  IO.println "    rules:    z ⇒ x  ;  x ⇒ y"
  IO.println "    defeater: target x⇒y, trigger y, undercutters []"
  IO.println "    facts at rung 0: {z}; defs at rung 0: {defeater}"
  IO.println "    no further admissions at any later rung"
  IO.println ""
  IO.println "    rung 0:  y concluded   (baseline, no defeaters fire)"
  IO.println "    rung 1:  y NOT concluded (defeater fires on rung-0 inference of y)"
  IO.println "    rung 2:  y concluded   (defeater doesn't fire — y ∉ ReflConclAt 1)"
  IO.println ""
  IO.println "    reflective_oscillation        ✓ (3 rungs witnessed)"
  IO.println "    osc_parity                    ✓ (∀ k: y at 2k, ¬y at 2k+1)"
  IO.println ""
  IO.println "Climber checks theory construction; defeater checks theory"
  IO.println "qualification. Same kernel discipline, opposite polarity."
